batch_size: 64
data_type: sequential
dataset: steam
decimals: 4
device: cpu
epoch: 20
eval_step: 5
eval_type: ranking
fair-rank: false
fairness_metrics:
- MinMaxRatio
- MMF
- GINI
- Entropy
fairness_type: Exposure
group_aggregation_threshold: 10
group_id: publisher:token
group_num: 1238
group_val: 5
history_field: history_behaviors
history_length: 5
item_domain: game
item_id: product_id:token
item_num: 1238
item_val: 5
label_id: label:float
label_threshold: 10
learning_rate: 0.001
log_name: steam-base-mf
mmf_eval_ratio: 0.5
model: mf
reprocess: true
sample_num: 200
sample_size: 1.0
stage: in-processing
store_scores: true
task: recommendation
test_ratio: 0.1
text_id: title:token
timestamp: timestamp:float
topk:
- 5
- 10
- 20
use_llm: false
user_id: user_id:token
user_num: 4446
user_val: 5
valid_ratio: 0.1
watch_metric: mmf@20
